version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: '%(levelprefix)s %(asctime)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    formatter: default
    class: logging.FileHandler
    filename: 'app_logs.log'  # The file where logs will be saved
loggers:
  uvicorn:
    handlers: [default, file]
    level: INFO
  fastapi:
    handlers: [default, file]
    level: DEBUG
  uvicorn.error:
    level: INFO
    handlers: [default, file]
    propagate: True
  uvicorn.access:
    level: INFO
    handlers: [default, file]
    propagate: False
